services:
  nodejs:
    image: node:alpine
    container_name: node-tutorials
    ports:
      - 3000:3000
    volumes:
      - ./:/app/code
    working_dir: /app/code
    command: 'sleep infinity'
    restart: always
    networks:
      tutorials_net:
        ipv4_address: 172.19.240.2

  mongo:
    image: mongo:7.0.12
    container_name: mongodb    
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      tutorials_net:
        ipv4_address: 172.19.240.3
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      tutorials_net:
        ipv4_address: 172.19.240.4
    

volumes:
  mongo-data:
    driver: local


networks:
  tutorials_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.19.240.0/24
          gateway: 172.19.240.1

